package com.mb.sociality.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mb.sociality.model.BBussinessCardAttribute;
import com.mb.sociality.model.BBussinessCardAttributeExample;

public interface BBussinessCardAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int countByExample(BBussinessCardAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int deleteByExample(BBussinessCardAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int insert(BBussinessCardAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int insertSelective(BBussinessCardAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	List<BBussinessCardAttribute> selectByExample(BBussinessCardAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	BBussinessCardAttribute selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BBussinessCardAttribute record, @Param("example") BBussinessCardAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int updateByExample(@Param("record") BBussinessCardAttribute record, @Param("example") BBussinessCardAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int updateByPrimaryKeySelective(BBussinessCardAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_bussiness_card_attribute
	 * @mbggenerated  Thu Jun 02 10:43:22 CST 2016
	 */
	int updateByPrimaryKey(BBussinessCardAttribute record);
	
	/*
	 * 自定義方法
	 */

	List<BBussinessCardAttribute> selectByLimit(@Param("offset") int offset, @Param("limit") int limit);
}