package com.mb.sociality.mapper;

import com.mb.sociality.model.BEnterpriseEmployee;
import com.mb.sociality.model.BEnterpriseEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BEnterpriseEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int countByExample(BEnterpriseEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int deleteByExample(BEnterpriseEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int insert(BEnterpriseEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int insertSelective(BEnterpriseEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    List<BEnterpriseEmployee> selectByExample(BEnterpriseEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    BEnterpriseEmployee selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") BEnterpriseEmployee record, @Param("example") BEnterpriseEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int updateByExample(@Param("record") BEnterpriseEmployee record, @Param("example") BEnterpriseEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int updateByPrimaryKeySelective(BEnterpriseEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_enterprise_employee
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    int updateByPrimaryKey(BEnterpriseEmployee record);
}