package com.mb.sociality.mapper;

import com.mb.sociality.model.BBussinessCardCategory;
import com.mb.sociality.model.BScheduledProject;
import com.mb.sociality.model.BScheduledProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BScheduledProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int countByExample(BScheduledProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int deleteByExample(BScheduledProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int insert(BScheduledProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int insertSelective(BScheduledProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	List<BScheduledProject> selectByExample(BScheduledProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	BScheduledProject selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BScheduledProject record, @Param("example") BScheduledProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int updateByExample(@Param("record") BScheduledProject record, @Param("example") BScheduledProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int updateByPrimaryKeySelective(BScheduledProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_scheduled_project
	 * @mbggenerated  Thu Jun 02 10:46:16 CST 2016
	 */
	int updateByPrimaryKey(BScheduledProject record);
	
	/*
	 * 自定義方法
	 */

	List<BScheduledProject> selectByLimit(@Param("offset") int offset, @Param("limit") int limit);
}