package com.mb.sociality.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mb.sociality.model.DBussinessCard;
import com.mb.sociality.model.DBussinessCardExample;

public interface DBussinessCardMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int countByExample(DBussinessCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int deleteByExample(DBussinessCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int insert(DBussinessCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int insertSelective(DBussinessCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	List<DBussinessCard> selectByExample(DBussinessCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	DBussinessCard selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DBussinessCard record, @Param("example") DBussinessCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int updateByExample(@Param("record") DBussinessCard record, @Param("example") DBussinessCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int updateByPrimaryKeySelective(DBussinessCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	int updateByPrimaryKey(DBussinessCard record);

	/*
	 * 自定義方法
	 */

	List<DBussinessCard> selectByLimit(@Param("offset") int offset, @Param("limit") int limit);
	
	List<DBussinessCard> selectByLike(@Param("offset") int offset, @Param("limit") int limit, 
			@Param("categoryGuid") String categoryGuid, @Param("attributeGuid") String attributeGuid, 
			@Param("statusGuid") String statusGuid, @Param("text") String text);
}