package com.mb.sociality.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mb.sociality.model.DBussinessCardSocical;
import com.mb.sociality.model.DBussinessCardSocicalExample;

public interface DBussinessCardSocicalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int countByExample(DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int deleteByExample(DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int insert(DBussinessCardSocical record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int insertSelective(DBussinessCardSocical record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	List<DBussinessCardSocical> selectByExampleWithBLOBs(DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	List<DBussinessCardSocical> selectByExample(DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	DBussinessCardSocical selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DBussinessCardSocical record, @Param("example") DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") DBussinessCardSocical record, @Param("example") DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int updateByExample(@Param("record") DBussinessCardSocical record, @Param("example") DBussinessCardSocicalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int updateByPrimaryKeySelective(DBussinessCardSocical record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(DBussinessCardSocical record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card_socical
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	int updateByPrimaryKey(DBussinessCardSocical record);
	
}