package com.mb.sociality.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mb.sociality.model.DScheduled;
import com.mb.sociality.model.DScheduledExample;

public interface DScheduledMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int countByExample(DScheduledExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int deleteByExample(DScheduledExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int insert(DScheduled record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int insertSelective(DScheduled record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	List<DScheduled> selectByExample(DScheduledExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	DScheduled selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DScheduled record, @Param("example") DScheduledExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int updateByExample(@Param("record") DScheduled record, @Param("example") DScheduledExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int updateByPrimaryKeySelective(DScheduled record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_scheduled
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	int updateByPrimaryKey(DScheduled record);
	
	/*
	 * 自定義方法
	 */

	List<DScheduled> selectByLimit(@Param("offset") int offset, @Param("limit") int limit);

	List<DScheduled> selectByLike(@Param("offset") int offset, @Param("limit") int limit, @Param("status") String status, 
			@Param("startTime") String startTime, @Param("endTime") String endTime, @Param("text") String text);
}