package com.mb.sociality.model;

import com.mb.sociality.base.BaseModel;

public class BBussinessCardAttribute extends BaseModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String guid;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bCorporationGuid;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bussiness_card_attribute.id
     *
     * @mbggenerated Mon May 30 10:40:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bussiness_card_attribute.name
     *
     * @mbggenerated Mon May 30 10:40:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bussiness_card_attribute.is_invalid
     *
     * @mbggenerated Mon May 30 10:40:53 CST 2016
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bussiness_card_attribute.id
     *
     * @param id the value for b_bussiness_card_attribute.id
     *
     * @mbggenerated Mon May 30 10:40:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bussiness_card_attribute.name
     *
     * @return the value of b_bussiness_card_attribute.name
     *
     * @mbggenerated Mon May 30 10:40:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bussiness_card_attribute.name
     *
     * @param name the value for b_bussiness_card_attribute.name
     *
     * @mbggenerated Mon May 30 10:40:53 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getbCorporationGuid() {
		return bCorporationGuid;
	}

	public void setbCorporationGuid(String bCorporationGuid) {
		this.bCorporationGuid = bCorporationGuid;
	}
}