package com.mb.sociality.model;

import java.util.Date;

public class BEnterpriseEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.id
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.b_enterprise_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String bEnterpriseGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.account
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.email
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.status
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.is_invalid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private Integer isInvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.creator_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String creatorGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.creator_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.creator_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private Date creatorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.modifier_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String modifierGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.modifier_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.modifier_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private Date modifierDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.invalid_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String invalidGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.invalid_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private String invalidName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.invalid_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    private Date invalidDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.guid
     *
     * @return the value of b_enterprise_employee.guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.guid
     *
     * @param guid the value for b_enterprise_employee.guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.id
     *
     * @return the value of b_enterprise_employee.id
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.id
     *
     * @param id the value for b_enterprise_employee.id
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.b_enterprise_guid
     *
     * @return the value of b_enterprise_employee.b_enterprise_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getbEnterpriseGuid() {
        return bEnterpriseGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.b_enterprise_guid
     *
     * @param bEnterpriseGuid the value for b_enterprise_employee.b_enterprise_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setbEnterpriseGuid(String bEnterpriseGuid) {
        this.bEnterpriseGuid = bEnterpriseGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.account
     *
     * @return the value of b_enterprise_employee.account
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.account
     *
     * @param account the value for b_enterprise_employee.account
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.email
     *
     * @return the value of b_enterprise_employee.email
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.email
     *
     * @param email the value for b_enterprise_employee.email
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.status
     *
     * @return the value of b_enterprise_employee.status
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.status
     *
     * @param status the value for b_enterprise_employee.status
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.is_invalid
     *
     * @return the value of b_enterprise_employee.is_invalid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public Integer getIsInvalid() {
        return isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.is_invalid
     *
     * @param isInvalid the value for b_enterprise_employee.is_invalid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setIsInvalid(Integer isInvalid) {
        this.isInvalid = isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.creator_guid
     *
     * @return the value of b_enterprise_employee.creator_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getCreatorGuid() {
        return creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.creator_guid
     *
     * @param creatorGuid the value for b_enterprise_employee.creator_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setCreatorGuid(String creatorGuid) {
        this.creatorGuid = creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.creator_name
     *
     * @return the value of b_enterprise_employee.creator_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.creator_name
     *
     * @param creatorName the value for b_enterprise_employee.creator_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.creator_date
     *
     * @return the value of b_enterprise_employee.creator_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.creator_date
     *
     * @param creatorDate the value for b_enterprise_employee.creator_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.modifier_guid
     *
     * @return the value of b_enterprise_employee.modifier_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getModifierGuid() {
        return modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.modifier_guid
     *
     * @param modifierGuid the value for b_enterprise_employee.modifier_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setModifierGuid(String modifierGuid) {
        this.modifierGuid = modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.modifier_name
     *
     * @return the value of b_enterprise_employee.modifier_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.modifier_name
     *
     * @param modifierName the value for b_enterprise_employee.modifier_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.modifier_date
     *
     * @return the value of b_enterprise_employee.modifier_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public Date getModifierDate() {
        return modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.modifier_date
     *
     * @param modifierDate the value for b_enterprise_employee.modifier_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setModifierDate(Date modifierDate) {
        this.modifierDate = modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.invalid_guid
     *
     * @return the value of b_enterprise_employee.invalid_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getInvalidGuid() {
        return invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.invalid_guid
     *
     * @param invalidGuid the value for b_enterprise_employee.invalid_guid
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setInvalidGuid(String invalidGuid) {
        this.invalidGuid = invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.invalid_name
     *
     * @return the value of b_enterprise_employee.invalid_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public String getInvalidName() {
        return invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.invalid_name
     *
     * @param invalidName the value for b_enterprise_employee.invalid_name
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setInvalidName(String invalidName) {
        this.invalidName = invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.invalid_date
     *
     * @return the value of b_enterprise_employee.invalid_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.invalid_date
     *
     * @param invalidDate the value for b_enterprise_employee.invalid_date
     *
     * @mbggenerated Thu Jun 02 17:43:22 CST 2016
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }
}