package com.mb.sociality.model;

import com.mb.sociality.base.BaseModel;

public class DBussinessCardSocical extends BaseModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String guid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_bussiness_card_socical.id
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_bussiness_card_socical.b_corporation_guid
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	private String dBussinessCardGuid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bCorporationGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_bussiness_card_socical.contact
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_bussiness_card_socical.is_invalid
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	private String remark ="";


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_bussiness_card_socical.id
	 * @return  the value of d_bussiness_card_socical.id
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_bussiness_card_socical.id
	 * @param id  the value for d_bussiness_card_socical.id
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}


	public String getdBussinessCardGuid() {
		return dBussinessCardGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_bussiness_card_socical.d_bussiness_card_guid
	 * @param dBussinessCardGuid  the value for d_bussiness_card_socical.d_bussiness_card_guid
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public void setdBussinessCardGuid(String dBussinessCardGuid) {
		this.dBussinessCardGuid = dBussinessCardGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_bussiness_card_socical.contact
	 * @return  the value of d_bussiness_card_socical.contact
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_bussiness_card_socical.contact
	 * @param contact  the value for d_bussiness_card_socical.contact
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_bussiness_card_socical.remark
	 * @return  the value of d_bussiness_card_socical.remark
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_bussiness_card_socical.remark
	 * @param remark  the value for d_bussiness_card_socical.remark
	 * @mbggenerated  Sat Jun 04 18:45:14 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getbCorporationGuid() {
		return bCorporationGuid;
	}

	public void setbCorporationGuid(String bCorporationGuid) {
		this.bCorporationGuid = bCorporationGuid;
	}
}