package com.mb.sociality.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DBussinessCardExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public DBussinessCardExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) { throw new RuntimeException("Value for condition cannot be null"); }
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) { throw new RuntimeException("Value for " + property + " cannot be null"); }
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) { throw new RuntimeException("Between values for " + property + " cannot be null"); }
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andGuidIsNull() {
			addCriterion("guid is null");
			return (Criteria) this;
		}

		public Criteria andGuidIsNotNull() {
			addCriterion("guid is not null");
			return (Criteria) this;
		}

		public Criteria andGuidEqualTo(String value) {
			addCriterion("guid =", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotEqualTo(String value) {
			addCriterion("guid <>", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidGreaterThan(String value) {
			addCriterion("guid >", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidGreaterThanOrEqualTo(String value) {
			addCriterion("guid >=", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLessThan(String value) {
			addCriterion("guid <", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLessThanOrEqualTo(String value) {
			addCriterion("guid <=", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLike(String value) {
			addCriterion("guid like", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotLike(String value) {
			addCriterion("guid not like", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidIn(List<String> values) {
			addCriterion("guid in", values, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotIn(List<String> values) {
			addCriterion("guid not in", values, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidBetween(String value1, String value2) {
			addCriterion("guid between", value1, value2, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotBetween(String value1, String value2) {
			addCriterion("guid not between", value1, value2, "guid");
			return (Criteria) this;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidIsNull() {
			addCriterion("b_corporation_guid is null");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidIsNotNull() {
			addCriterion("b_corporation_guid is not null");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidEqualTo(String value) {
			addCriterion("b_corporation_guid =", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidNotEqualTo(String value) {
			addCriterion("b_corporation_guid <>", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidGreaterThan(String value) {
			addCriterion("b_corporation_guid >", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidGreaterThanOrEqualTo(String value) {
			addCriterion("b_corporation_guid >=", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidLessThan(String value) {
			addCriterion("b_corporation_guid <", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidLessThanOrEqualTo(String value) {
			addCriterion("b_corporation_guid <=", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidLike(String value) {
			addCriterion("b_corporation_guid like", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidNotLike(String value) {
			addCriterion("b_corporation_guid not like", value, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidIn(List<String> values) {
			addCriterion("b_corporation_guid in", values, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidNotIn(List<String> values) {
			addCriterion("b_corporation_guid not in", values, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidBetween(String value1, String value2) {
			addCriterion("b_corporation_guid between", value1, value2, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBCorporationGuidNotBetween(String value1, String value2) {
			addCriterion("b_corporation_guid not between", value1, value2, "bCorporationGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidIsNull() {
			addCriterion("b_bussiness_card_category_guid is null");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidIsNotNull() {
			addCriterion("b_bussiness_card_category_guid is not null");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidEqualTo(String value) {
			addCriterion("b_bussiness_card_category_guid =", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidNotEqualTo(String value) {
			addCriterion("b_bussiness_card_category_guid <>", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidGreaterThan(String value) {
			addCriterion("b_bussiness_card_category_guid >", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidGreaterThanOrEqualTo(String value) {
			addCriterion("b_bussiness_card_category_guid >=", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidLessThan(String value) {
			addCriterion("b_bussiness_card_category_guid <", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidLessThanOrEqualTo(String value) {
			addCriterion("b_bussiness_card_category_guid <=", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidLike(String value) {
			addCriterion("b_bussiness_card_category_guid like", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidNotLike(String value) {
			addCriterion("b_bussiness_card_category_guid not like", value, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidIn(List<String> values) {
			addCriterion("b_bussiness_card_category_guid in", values, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidNotIn(List<String> values) {
			addCriterion("b_bussiness_card_category_guid not in", values, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidBetween(String value1, String value2) {
			addCriterion("b_bussiness_card_category_guid between", value1, value2, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardCategoryGuidNotBetween(String value1, String value2) {
			addCriterion("b_bussiness_card_category_guid not between", value1, value2, "bBussinessCardCategoryGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidIsNull() {
			addCriterion("b_bussiness_card_status_guid is null");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidIsNotNull() {
			addCriterion("b_bussiness_card_status_guid is not null");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidEqualTo(String value) {
			addCriterion("b_bussiness_card_status_guid =", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidNotEqualTo(String value) {
			addCriterion("b_bussiness_card_status_guid <>", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidGreaterThan(String value) {
			addCriterion("b_bussiness_card_status_guid >", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidGreaterThanOrEqualTo(String value) {
			addCriterion("b_bussiness_card_status_guid >=", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidLessThan(String value) {
			addCriterion("b_bussiness_card_status_guid <", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidLessThanOrEqualTo(String value) {
			addCriterion("b_bussiness_card_status_guid <=", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidLike(String value) {
			addCriterion("b_bussiness_card_status_guid like", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidNotLike(String value) {
			addCriterion("b_bussiness_card_status_guid not like", value, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidIn(List<String> values) {
			addCriterion("b_bussiness_card_status_guid in", values, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidNotIn(List<String> values) {
			addCriterion("b_bussiness_card_status_guid not in", values, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidBetween(String value1, String value2) {
			addCriterion("b_bussiness_card_status_guid between", value1, value2, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardStatusGuidNotBetween(String value1, String value2) {
			addCriterion("b_bussiness_card_status_guid not between", value1, value2, "bBussinessCardStatusGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidIsNull() {
			addCriterion("b_bussiness_card_attribute_guid is null");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidIsNotNull() {
			addCriterion("b_bussiness_card_attribute_guid is not null");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidEqualTo(String value) {
			addCriterion("b_bussiness_card_attribute_guid =", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidNotEqualTo(String value) {
			addCriterion("b_bussiness_card_attribute_guid <>", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidGreaterThan(String value) {
			addCriterion("b_bussiness_card_attribute_guid >", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidGreaterThanOrEqualTo(String value) {
			addCriterion("b_bussiness_card_attribute_guid >=", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidLessThan(String value) {
			addCriterion("b_bussiness_card_attribute_guid <", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidLessThanOrEqualTo(String value) {
			addCriterion("b_bussiness_card_attribute_guid <=", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidLike(String value) {
			addCriterion("b_bussiness_card_attribute_guid like", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidNotLike(String value) {
			addCriterion("b_bussiness_card_attribute_guid not like", value, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidIn(List<String> values) {
			addCriterion("b_bussiness_card_attribute_guid in", values, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidNotIn(List<String> values) {
			addCriterion("b_bussiness_card_attribute_guid not in", values, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidBetween(String value1, String value2) {
			addCriterion("b_bussiness_card_attribute_guid between", value1, value2, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBBussinessCardAttributeGuidNotBetween(String value1, String value2) {
			addCriterion("b_bussiness_card_attribute_guid not between", value1, value2, "bBussinessCardAttributeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidIsNull() {
			addCriterion("b_enterprise_employee_guid is null");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidIsNotNull() {
			addCriterion("b_enterprise_employee_guid is not null");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidEqualTo(String value) {
			addCriterion("b_enterprise_employee_guid =", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidNotEqualTo(String value) {
			addCriterion("b_enterprise_employee_guid <>", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidGreaterThan(String value) {
			addCriterion("b_enterprise_employee_guid >", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidGreaterThanOrEqualTo(String value) {
			addCriterion("b_enterprise_employee_guid >=", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidLessThan(String value) {
			addCriterion("b_enterprise_employee_guid <", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidLessThanOrEqualTo(String value) {
			addCriterion("b_enterprise_employee_guid <=", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidLike(String value) {
			addCriterion("b_enterprise_employee_guid like", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidNotLike(String value) {
			addCriterion("b_enterprise_employee_guid not like", value, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidIn(List<String> values) {
			addCriterion("b_enterprise_employee_guid in", values, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidNotIn(List<String> values) {
			addCriterion("b_enterprise_employee_guid not in", values, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidBetween(String value1, String value2) {
			addCriterion("b_enterprise_employee_guid between", value1, value2, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andBEnterpriseEmployeeGuidNotBetween(String value1, String value2) {
			addCriterion("b_enterprise_employee_guid not between", value1, value2, "bEnterpriseEmployeeGuid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickname is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickname is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickname =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickname <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickname >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickname >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickname <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickname <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickname like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickname not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickname in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickname not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickname between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickname not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberIsNull() {
			addCriterion("cellphone_number is null");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberIsNotNull() {
			addCriterion("cellphone_number is not null");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberEqualTo(String value) {
			addCriterion("cellphone_number =", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotEqualTo(String value) {
			addCriterion("cellphone_number <>", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberGreaterThan(String value) {
			addCriterion("cellphone_number >", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("cellphone_number >=", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberLessThan(String value) {
			addCriterion("cellphone_number <", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberLessThanOrEqualTo(String value) {
			addCriterion("cellphone_number <=", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberLike(String value) {
			addCriterion("cellphone_number like", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotLike(String value) {
			addCriterion("cellphone_number not like", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberIn(List<String> values) {
			addCriterion("cellphone_number in", values, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotIn(List<String> values) {
			addCriterion("cellphone_number not in", values, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberBetween(String value1, String value2) {
			addCriterion("cellphone_number between", value1, value2, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotBetween(String value1, String value2) {
			addCriterion("cellphone_number not between", value1, value2, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressIsNull() {
			addCriterion("company_address is null");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressIsNotNull() {
			addCriterion("company_address is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressEqualTo(String value) {
			addCriterion("company_address =", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressNotEqualTo(String value) {
			addCriterion("company_address <>", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressGreaterThan(String value) {
			addCriterion("company_address >", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
			addCriterion("company_address >=", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressLessThan(String value) {
			addCriterion("company_address <", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
			addCriterion("company_address <=", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressLike(String value) {
			addCriterion("company_address like", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressNotLike(String value) {
			addCriterion("company_address not like", value, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressIn(List<String> values) {
			addCriterion("company_address in", values, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressNotIn(List<String> values) {
			addCriterion("company_address not in", values, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressBetween(String value1, String value2) {
			addCriterion("company_address between", value1, value2, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyAddressNotBetween(String value1, String value2) {
			addCriterion("company_address not between", value1, value2, "companyAddress");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberIsNull() {
			addCriterion("company_phone_number is null");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberIsNotNull() {
			addCriterion("company_phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberEqualTo(String value) {
			addCriterion("company_phone_number =", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberNotEqualTo(String value) {
			addCriterion("company_phone_number <>", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberGreaterThan(String value) {
			addCriterion("company_phone_number >", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("company_phone_number >=", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberLessThan(String value) {
			addCriterion("company_phone_number <", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("company_phone_number <=", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberLike(String value) {
			addCriterion("company_phone_number like", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberNotLike(String value) {
			addCriterion("company_phone_number not like", value, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberIn(List<String> values) {
			addCriterion("company_phone_number in", values, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberNotIn(List<String> values) {
			addCriterion("company_phone_number not in", values, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberBetween(String value1, String value2) {
			addCriterion("company_phone_number between", value1, value2, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCompanyPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("company_phone_number not between", value1, value2, "companyPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andFeatureIsNull() {
			addCriterion("feature is null");
			return (Criteria) this;
		}

		public Criteria andFeatureIsNotNull() {
			addCriterion("feature is not null");
			return (Criteria) this;
		}

		public Criteria andFeatureEqualTo(String value) {
			addCriterion("feature =", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotEqualTo(String value) {
			addCriterion("feature <>", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureGreaterThan(String value) {
			addCriterion("feature >", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureGreaterThanOrEqualTo(String value) {
			addCriterion("feature >=", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLessThan(String value) {
			addCriterion("feature <", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLessThanOrEqualTo(String value) {
			addCriterion("feature <=", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLike(String value) {
			addCriterion("feature like", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotLike(String value) {
			addCriterion("feature not like", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureIn(List<String> values) {
			addCriterion("feature in", values, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotIn(List<String> values) {
			addCriterion("feature not in", values, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureBetween(String value1, String value2) {
			addCriterion("feature between", value1, value2, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotBetween(String value1, String value2) {
			addCriterion("feature not between", value1, value2, "feature");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearIsNull() {
			addCriterion("birthday_year is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearIsNotNull() {
			addCriterion("birthday_year is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearEqualTo(String value) {
			addCriterion("birthday_year =", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearNotEqualTo(String value) {
			addCriterion("birthday_year <>", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearGreaterThan(String value) {
			addCriterion("birthday_year >", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearGreaterThanOrEqualTo(String value) {
			addCriterion("birthday_year >=", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearLessThan(String value) {
			addCriterion("birthday_year <", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearLessThanOrEqualTo(String value) {
			addCriterion("birthday_year <=", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearLike(String value) {
			addCriterion("birthday_year like", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearNotLike(String value) {
			addCriterion("birthday_year not like", value, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearIn(List<String> values) {
			addCriterion("birthday_year in", values, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearNotIn(List<String> values) {
			addCriterion("birthday_year not in", values, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearBetween(String value1, String value2) {
			addCriterion("birthday_year between", value1, value2, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayYearNotBetween(String value1, String value2) {
			addCriterion("birthday_year not between", value1, value2, "birthdayYear");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthIsNull() {
			addCriterion("birthday_month is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthIsNotNull() {
			addCriterion("birthday_month is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthEqualTo(String value) {
			addCriterion("birthday_month =", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthNotEqualTo(String value) {
			addCriterion("birthday_month <>", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthGreaterThan(String value) {
			addCriterion("birthday_month >", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthGreaterThanOrEqualTo(String value) {
			addCriterion("birthday_month >=", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthLessThan(String value) {
			addCriterion("birthday_month <", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthLessThanOrEqualTo(String value) {
			addCriterion("birthday_month <=", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthLike(String value) {
			addCriterion("birthday_month like", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthNotLike(String value) {
			addCriterion("birthday_month not like", value, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthIn(List<String> values) {
			addCriterion("birthday_month in", values, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthNotIn(List<String> values) {
			addCriterion("birthday_month not in", values, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthBetween(String value1, String value2) {
			addCriterion("birthday_month between", value1, value2, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayMonthNotBetween(String value1, String value2) {
			addCriterion("birthday_month not between", value1, value2, "birthdayMonth");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateIsNull() {
			addCriterion("birthday_date is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateIsNotNull() {
			addCriterion("birthday_date is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateEqualTo(String value) {
			addCriterion("birthday_date =", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateNotEqualTo(String value) {
			addCriterion("birthday_date <>", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateGreaterThan(String value) {
			addCriterion("birthday_date >", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateGreaterThanOrEqualTo(String value) {
			addCriterion("birthday_date >=", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateLessThan(String value) {
			addCriterion("birthday_date <", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateLessThanOrEqualTo(String value) {
			addCriterion("birthday_date <=", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateLike(String value) {
			addCriterion("birthday_date like", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateNotLike(String value) {
			addCriterion("birthday_date not like", value, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateIn(List<String> values) {
			addCriterion("birthday_date in", values, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateNotIn(List<String> values) {
			addCriterion("birthday_date not in", values, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateBetween(String value1, String value2) {
			addCriterion("birthday_date between", value1, value2, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andBirthdayDateNotBetween(String value1, String value2) {
			addCriterion("birthday_date not between", value1, value2, "birthdayDate");
			return (Criteria) this;
		}

		public Criteria andMarrageIsNull() {
			addCriterion("marrage is null");
			return (Criteria) this;
		}

		public Criteria andMarrageIsNotNull() {
			addCriterion("marrage is not null");
			return (Criteria) this;
		}

		public Criteria andMarrageEqualTo(String value) {
			addCriterion("marrage =", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageNotEqualTo(String value) {
			addCriterion("marrage <>", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageGreaterThan(String value) {
			addCriterion("marrage >", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageGreaterThanOrEqualTo(String value) {
			addCriterion("marrage >=", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageLessThan(String value) {
			addCriterion("marrage <", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageLessThanOrEqualTo(String value) {
			addCriterion("marrage <=", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageLike(String value) {
			addCriterion("marrage like", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageNotLike(String value) {
			addCriterion("marrage not like", value, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageIn(List<String> values) {
			addCriterion("marrage in", values, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageNotIn(List<String> values) {
			addCriterion("marrage not in", values, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageBetween(String value1, String value2) {
			addCriterion("marrage between", value1, value2, "marrage");
			return (Criteria) this;
		}

		public Criteria andMarrageNotBetween(String value1, String value2) {
			addCriterion("marrage not between", value1, value2, "marrage");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeIsNull() {
			addCriterion("first_meet_time is null");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeIsNotNull() {
			addCriterion("first_meet_time is not null");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeEqualTo(Date value) {
			addCriterion("first_meet_time =", value, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeNotEqualTo(Date value) {
			addCriterion("first_meet_time <>", value, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeGreaterThan(Date value) {
			addCriterion("first_meet_time >", value, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("first_meet_time >=", value, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeLessThan(Date value) {
			addCriterion("first_meet_time <", value, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeLessThanOrEqualTo(Date value) {
			addCriterion("first_meet_time <=", value, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeIn(List<Date> values) {
			addCriterion("first_meet_time in", values, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeNotIn(List<Date> values) {
			addCriterion("first_meet_time not in", values, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeBetween(Date value1, Date value2) {
			addCriterion("first_meet_time between", value1, value2, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetTimeNotBetween(Date value1, Date value2) {
			addCriterion("first_meet_time not between", value1, value2, "firstMeetTime");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationIsNull() {
			addCriterion("first_meet_location is null");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationIsNotNull() {
			addCriterion("first_meet_location is not null");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationEqualTo(String value) {
			addCriterion("first_meet_location =", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationNotEqualTo(String value) {
			addCriterion("first_meet_location <>", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationGreaterThan(String value) {
			addCriterion("first_meet_location >", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationGreaterThanOrEqualTo(String value) {
			addCriterion("first_meet_location >=", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationLessThan(String value) {
			addCriterion("first_meet_location <", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationLessThanOrEqualTo(String value) {
			addCriterion("first_meet_location <=", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationLike(String value) {
			addCriterion("first_meet_location like", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationNotLike(String value) {
			addCriterion("first_meet_location not like", value, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationIn(List<String> values) {
			addCriterion("first_meet_location in", values, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationNotIn(List<String> values) {
			addCriterion("first_meet_location not in", values, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationBetween(String value1, String value2) {
			addCriterion("first_meet_location between", value1, value2, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andFirstMeetLocationNotBetween(String value1, String value2) {
			addCriterion("first_meet_location not between", value1, value2, "firstMeetLocation");
			return (Criteria) this;
		}

		public Criteria andImageIsNull() {
			addCriterion("image is null");
			return (Criteria) this;
		}

		public Criteria andImageIsNotNull() {
			addCriterion("image is not null");
			return (Criteria) this;
		}

		public Criteria andImageEqualTo(String value) {
			addCriterion("image =", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotEqualTo(String value) {
			addCriterion("image <>", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageGreaterThan(String value) {
			addCriterion("image >", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageGreaterThanOrEqualTo(String value) {
			addCriterion("image >=", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLessThan(String value) {
			addCriterion("image <", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLessThanOrEqualTo(String value) {
			addCriterion("image <=", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLike(String value) {
			addCriterion("image like", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotLike(String value) {
			addCriterion("image not like", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageIn(List<String> values) {
			addCriterion("image in", values, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotIn(List<String> values) {
			addCriterion("image not in", values, "image");
			return (Criteria) this;
		}

		public Criteria andImageBetween(String value1, String value2) {
			addCriterion("image between", value1, value2, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotBetween(String value1, String value2) {
			addCriterion("image not between", value1, value2, "image");
			return (Criteria) this;
		}

		public Criteria andImagePathIsNull() {
			addCriterion("image_path is null");
			return (Criteria) this;
		}

		public Criteria andImagePathIsNotNull() {
			addCriterion("image_path is not null");
			return (Criteria) this;
		}

		public Criteria andImagePathEqualTo(String value) {
			addCriterion("image_path =", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathNotEqualTo(String value) {
			addCriterion("image_path <>", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathGreaterThan(String value) {
			addCriterion("image_path >", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathGreaterThanOrEqualTo(String value) {
			addCriterion("image_path >=", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathLessThan(String value) {
			addCriterion("image_path <", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathLessThanOrEqualTo(String value) {
			addCriterion("image_path <=", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathLike(String value) {
			addCriterion("image_path like", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathNotLike(String value) {
			addCriterion("image_path not like", value, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathIn(List<String> values) {
			addCriterion("image_path in", values, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathNotIn(List<String> values) {
			addCriterion("image_path not in", values, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathBetween(String value1, String value2) {
			addCriterion("image_path between", value1, value2, "imagePath");
			return (Criteria) this;
		}

		public Criteria andImagePathNotBetween(String value1, String value2) {
			addCriterion("image_path not between", value1, value2, "imagePath");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andIsInvalidIsNull() {
			addCriterion("is_invalid is null");
			return (Criteria) this;
		}

		public Criteria andIsInvalidIsNotNull() {
			addCriterion("is_invalid is not null");
			return (Criteria) this;
		}

		public Criteria andIsInvalidEqualTo(Integer value) {
			addCriterion("is_invalid =", value, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidNotEqualTo(Integer value) {
			addCriterion("is_invalid <>", value, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidGreaterThan(Integer value) {
			addCriterion("is_invalid >", value, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_invalid >=", value, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidLessThan(Integer value) {
			addCriterion("is_invalid <", value, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidLessThanOrEqualTo(Integer value) {
			addCriterion("is_invalid <=", value, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidIn(List<Integer> values) {
			addCriterion("is_invalid in", values, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidNotIn(List<Integer> values) {
			addCriterion("is_invalid not in", values, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidBetween(Integer value1, Integer value2) {
			addCriterion("is_invalid between", value1, value2, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andIsInvalidNotBetween(Integer value1, Integer value2) {
			addCriterion("is_invalid not between", value1, value2, "isInvalid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidIsNull() {
			addCriterion("creator_guid is null");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidIsNotNull() {
			addCriterion("creator_guid is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidEqualTo(String value) {
			addCriterion("creator_guid =", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidNotEqualTo(String value) {
			addCriterion("creator_guid <>", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidGreaterThan(String value) {
			addCriterion("creator_guid >", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidGreaterThanOrEqualTo(String value) {
			addCriterion("creator_guid >=", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidLessThan(String value) {
			addCriterion("creator_guid <", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidLessThanOrEqualTo(String value) {
			addCriterion("creator_guid <=", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidLike(String value) {
			addCriterion("creator_guid like", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidNotLike(String value) {
			addCriterion("creator_guid not like", value, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidIn(List<String> values) {
			addCriterion("creator_guid in", values, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidNotIn(List<String> values) {
			addCriterion("creator_guid not in", values, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidBetween(String value1, String value2) {
			addCriterion("creator_guid between", value1, value2, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorGuidNotBetween(String value1, String value2) {
			addCriterion("creator_guid not between", value1, value2, "creatorGuid");
			return (Criteria) this;
		}

		public Criteria andCreatorNameIsNull() {
			addCriterion("creator_name is null");
			return (Criteria) this;
		}

		public Criteria andCreatorNameIsNotNull() {
			addCriterion("creator_name is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorNameEqualTo(String value) {
			addCriterion("creator_name =", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameNotEqualTo(String value) {
			addCriterion("creator_name <>", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameGreaterThan(String value) {
			addCriterion("creator_name >", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameGreaterThanOrEqualTo(String value) {
			addCriterion("creator_name >=", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameLessThan(String value) {
			addCriterion("creator_name <", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameLessThanOrEqualTo(String value) {
			addCriterion("creator_name <=", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameLike(String value) {
			addCriterion("creator_name like", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameNotLike(String value) {
			addCriterion("creator_name not like", value, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameIn(List<String> values) {
			addCriterion("creator_name in", values, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameNotIn(List<String> values) {
			addCriterion("creator_name not in", values, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameBetween(String value1, String value2) {
			addCriterion("creator_name between", value1, value2, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorNameNotBetween(String value1, String value2) {
			addCriterion("creator_name not between", value1, value2, "creatorName");
			return (Criteria) this;
		}

		public Criteria andCreatorDateIsNull() {
			addCriterion("creator_date is null");
			return (Criteria) this;
		}

		public Criteria andCreatorDateIsNotNull() {
			addCriterion("creator_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorDateEqualTo(Date value) {
			addCriterion("creator_date =", value, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateNotEqualTo(Date value) {
			addCriterion("creator_date <>", value, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateGreaterThan(Date value) {
			addCriterion("creator_date >", value, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateGreaterThanOrEqualTo(Date value) {
			addCriterion("creator_date >=", value, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateLessThan(Date value) {
			addCriterion("creator_date <", value, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateLessThanOrEqualTo(Date value) {
			addCriterion("creator_date <=", value, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateIn(List<Date> values) {
			addCriterion("creator_date in", values, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateNotIn(List<Date> values) {
			addCriterion("creator_date not in", values, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateBetween(Date value1, Date value2) {
			addCriterion("creator_date between", value1, value2, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andCreatorDateNotBetween(Date value1, Date value2) {
			addCriterion("creator_date not between", value1, value2, "creatorDate");
			return (Criteria) this;
		}

		public Criteria andModifierGuidIsNull() {
			addCriterion("modifier_guid is null");
			return (Criteria) this;
		}

		public Criteria andModifierGuidIsNotNull() {
			addCriterion("modifier_guid is not null");
			return (Criteria) this;
		}

		public Criteria andModifierGuidEqualTo(String value) {
			addCriterion("modifier_guid =", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidNotEqualTo(String value) {
			addCriterion("modifier_guid <>", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidGreaterThan(String value) {
			addCriterion("modifier_guid >", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidGreaterThanOrEqualTo(String value) {
			addCriterion("modifier_guid >=", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidLessThan(String value) {
			addCriterion("modifier_guid <", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidLessThanOrEqualTo(String value) {
			addCriterion("modifier_guid <=", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidLike(String value) {
			addCriterion("modifier_guid like", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidNotLike(String value) {
			addCriterion("modifier_guid not like", value, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidIn(List<String> values) {
			addCriterion("modifier_guid in", values, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidNotIn(List<String> values) {
			addCriterion("modifier_guid not in", values, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidBetween(String value1, String value2) {
			addCriterion("modifier_guid between", value1, value2, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierGuidNotBetween(String value1, String value2) {
			addCriterion("modifier_guid not between", value1, value2, "modifierGuid");
			return (Criteria) this;
		}

		public Criteria andModifierNameIsNull() {
			addCriterion("modifier_name is null");
			return (Criteria) this;
		}

		public Criteria andModifierNameIsNotNull() {
			addCriterion("modifier_name is not null");
			return (Criteria) this;
		}

		public Criteria andModifierNameEqualTo(String value) {
			addCriterion("modifier_name =", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameNotEqualTo(String value) {
			addCriterion("modifier_name <>", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameGreaterThan(String value) {
			addCriterion("modifier_name >", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameGreaterThanOrEqualTo(String value) {
			addCriterion("modifier_name >=", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameLessThan(String value) {
			addCriterion("modifier_name <", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameLessThanOrEqualTo(String value) {
			addCriterion("modifier_name <=", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameLike(String value) {
			addCriterion("modifier_name like", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameNotLike(String value) {
			addCriterion("modifier_name not like", value, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameIn(List<String> values) {
			addCriterion("modifier_name in", values, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameNotIn(List<String> values) {
			addCriterion("modifier_name not in", values, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameBetween(String value1, String value2) {
			addCriterion("modifier_name between", value1, value2, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierNameNotBetween(String value1, String value2) {
			addCriterion("modifier_name not between", value1, value2, "modifierName");
			return (Criteria) this;
		}

		public Criteria andModifierDateIsNull() {
			addCriterion("modifier_date is null");
			return (Criteria) this;
		}

		public Criteria andModifierDateIsNotNull() {
			addCriterion("modifier_date is not null");
			return (Criteria) this;
		}

		public Criteria andModifierDateEqualTo(Date value) {
			addCriterion("modifier_date =", value, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateNotEqualTo(Date value) {
			addCriterion("modifier_date <>", value, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateGreaterThan(Date value) {
			addCriterion("modifier_date >", value, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateGreaterThanOrEqualTo(Date value) {
			addCriterion("modifier_date >=", value, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateLessThan(Date value) {
			addCriterion("modifier_date <", value, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateLessThanOrEqualTo(Date value) {
			addCriterion("modifier_date <=", value, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateIn(List<Date> values) {
			addCriterion("modifier_date in", values, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateNotIn(List<Date> values) {
			addCriterion("modifier_date not in", values, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateBetween(Date value1, Date value2) {
			addCriterion("modifier_date between", value1, value2, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andModifierDateNotBetween(Date value1, Date value2) {
			addCriterion("modifier_date not between", value1, value2, "modifierDate");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidIsNull() {
			addCriterion("invalid_guid is null");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidIsNotNull() {
			addCriterion("invalid_guid is not null");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidEqualTo(String value) {
			addCriterion("invalid_guid =", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidNotEqualTo(String value) {
			addCriterion("invalid_guid <>", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidGreaterThan(String value) {
			addCriterion("invalid_guid >", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidGreaterThanOrEqualTo(String value) {
			addCriterion("invalid_guid >=", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidLessThan(String value) {
			addCriterion("invalid_guid <", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidLessThanOrEqualTo(String value) {
			addCriterion("invalid_guid <=", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidLike(String value) {
			addCriterion("invalid_guid like", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidNotLike(String value) {
			addCriterion("invalid_guid not like", value, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidIn(List<String> values) {
			addCriterion("invalid_guid in", values, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidNotIn(List<String> values) {
			addCriterion("invalid_guid not in", values, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidBetween(String value1, String value2) {
			addCriterion("invalid_guid between", value1, value2, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidGuidNotBetween(String value1, String value2) {
			addCriterion("invalid_guid not between", value1, value2, "invalidGuid");
			return (Criteria) this;
		}

		public Criteria andInvalidNameIsNull() {
			addCriterion("invalid_name is null");
			return (Criteria) this;
		}

		public Criteria andInvalidNameIsNotNull() {
			addCriterion("invalid_name is not null");
			return (Criteria) this;
		}

		public Criteria andInvalidNameEqualTo(String value) {
			addCriterion("invalid_name =", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameNotEqualTo(String value) {
			addCriterion("invalid_name <>", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameGreaterThan(String value) {
			addCriterion("invalid_name >", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameGreaterThanOrEqualTo(String value) {
			addCriterion("invalid_name >=", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameLessThan(String value) {
			addCriterion("invalid_name <", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameLessThanOrEqualTo(String value) {
			addCriterion("invalid_name <=", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameLike(String value) {
			addCriterion("invalid_name like", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameNotLike(String value) {
			addCriterion("invalid_name not like", value, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameIn(List<String> values) {
			addCriterion("invalid_name in", values, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameNotIn(List<String> values) {
			addCriterion("invalid_name not in", values, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameBetween(String value1, String value2) {
			addCriterion("invalid_name between", value1, value2, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidNameNotBetween(String value1, String value2) {
			addCriterion("invalid_name not between", value1, value2, "invalidName");
			return (Criteria) this;
		}

		public Criteria andInvalidDateIsNull() {
			addCriterion("invalid_date is null");
			return (Criteria) this;
		}

		public Criteria andInvalidDateIsNotNull() {
			addCriterion("invalid_date is not null");
			return (Criteria) this;
		}

		public Criteria andInvalidDateEqualTo(Date value) {
			addCriterion("invalid_date =", value, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateNotEqualTo(Date value) {
			addCriterion("invalid_date <>", value, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateGreaterThan(Date value) {
			addCriterion("invalid_date >", value, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateGreaterThanOrEqualTo(Date value) {
			addCriterion("invalid_date >=", value, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateLessThan(Date value) {
			addCriterion("invalid_date <", value, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateLessThanOrEqualTo(Date value) {
			addCriterion("invalid_date <=", value, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateIn(List<Date> values) {
			addCriterion("invalid_date in", values, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateNotIn(List<Date> values) {
			addCriterion("invalid_date not in", values, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateBetween(Date value1, Date value2) {
			addCriterion("invalid_date between", value1, value2, "invalidDate");
			return (Criteria) this;
		}

		public Criteria andInvalidDateNotBetween(Date value1, Date value2) {
			addCriterion("invalid_date not between", value1, value2, "invalidDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table d_bussiness_card
	 * @mbggenerated  Thu Jun 16 10:14:01 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_bussiness_card
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 02 12:00:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}