package com.mb.sociality.model;

import java.util.Date;

import com.mb.sociality.base.BaseModel;

import lombok.Getter;
import lombok.Setter;

public class DScheduled extends BaseModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String guid;

	private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bCorporationGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.b_corporation_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */

	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.b_scheduled_project_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String bScheduledProjectGuid = null;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.company_name
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String companyName = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.name
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String name = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.nickname
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String nickname = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.d_bussiness_card_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String dBussinessCardGuid = null;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.start_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.end_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.email_notify_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private Date emailNotifyTime = new Date();
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.alarm_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private Date alarmTime = new Date();
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.destination
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String destination;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.souvenir
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String souvenir = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.status
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private Integer status = 1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.summary
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String summary = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.record_of_meeting
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	private String recordOfMeeting = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_scheduled.is_invalid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */

	@Getter @Setter
	private String startTimeString;
	@Getter @Setter
	private String endTimeString;
	@Getter @Setter
	private String emailNotifyTimeString;
	@Getter @Setter
	private String alarmTimeString;

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.id
	 * @param id  the value for d_scheduled.id
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}


	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.title
	 * @param title  the value for d_scheduled.title
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.b_scheduled_project_guid
	 * @return  the value of d_scheduled.b_scheduled_project_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getbScheduledProjectGuid() {
		return bScheduledProjectGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.b_scheduled_project_guid
	 * @param bScheduledProjectGuid  the value for d_scheduled.b_scheduled_project_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setbScheduledProjectGuid(String bScheduledProjectGuid) {
		this.bScheduledProjectGuid = bScheduledProjectGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.company_name
	 * @return  the value of d_scheduled.company_name
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.company_name
	 * @param companyName  the value for d_scheduled.company_name
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.name
	 * @return  the value of d_scheduled.name
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.name
	 * @param name  the value for d_scheduled.name
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.nickname
	 * @return  the value of d_scheduled.nickname
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.nickname
	 * @param nickname  the value for d_scheduled.nickname
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.d_bussiness_card_guid
	 * @return  the value of d_scheduled.d_bussiness_card_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getdBussinessCardGuid() {
		return dBussinessCardGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.d_bussiness_card_guid
	 * @param dBussinessCardGuid  the value for d_scheduled.d_bussiness_card_guid
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setdBussinessCardGuid(String dBussinessCardGuid) {
		this.dBussinessCardGuid = dBussinessCardGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.start_time
	 * @return  the value of d_scheduled.start_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.start_time
	 * @param startTime  the value for d_scheduled.start_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.end_time
	 * @return  the value of d_scheduled.end_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.end_time
	 * @param endTime  the value for d_scheduled.end_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.email_notify_time
	 * @return  the value of d_scheduled.email_notify_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public Date getEmailNotifyTime() {
		return emailNotifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.email_notify_time
	 * @param emailNotifyTime  the value for d_scheduled.email_notify_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setEmailNotifyTime(Date emailNotifyTime) {
		this.emailNotifyTime = emailNotifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.alarm_time
	 * @return  the value of d_scheduled.alarm_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public Date getAlarmTime() {
		return alarmTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.alarm_time
	 * @param alarmTime  the value for d_scheduled.alarm_time
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setAlarmTime(Date alarmTime) {
		this.alarmTime = alarmTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.destination
	 * @return  the value of d_scheduled.destination
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getDestination() {
		return destination;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.destination
	 * @param destination  the value for d_scheduled.destination
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setDestination(String destination) {
		this.destination = destination;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.souvenir
	 * @return  the value of d_scheduled.souvenir
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getSouvenir() {
		return souvenir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.souvenir
	 * @param souvenir  the value for d_scheduled.souvenir
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setSouvenir(String souvenir) {
		this.souvenir = souvenir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.status
	 * @return  the value of d_scheduled.status
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.status
	 * @param status  the value for d_scheduled.status
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.summary
	 * @return  the value of d_scheduled.summary
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.summary
	 * @param summary  the value for d_scheduled.summary
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_scheduled.record_of_meeting
	 * @return  the value of d_scheduled.record_of_meeting
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public String getRecordOfMeeting() {
		return recordOfMeeting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_scheduled.record_of_meeting
	 * @param recordOfMeeting  the value for d_scheduled.record_of_meeting
	 * @mbggenerated  Tue Jun 07 17:11:26 CST 2016
	 */
	public void setRecordOfMeeting(String recordOfMeeting) {
		this.recordOfMeeting = recordOfMeeting;
	}

	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getbCorporationGuid() {
		return bCorporationGuid;
	}

	public void setbCorporationGuid(String bCorporationGuid) {
		this.bCorporationGuid = bCorporationGuid;
	}

}